plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.12'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '9.0.0'
    id 'com.gorylenko.gradle-git-properties' version '4.0.1'
}

def gitHash = providers.exec {
    commandLine 'git', 'rev-parse', '--short', 'HEAD'
}.standardOutput.asText.get().trim()

version = gitHash
group = project.findProperty('maven_group') ?: 'net.paradise_client'

base {
    archivesName = project.findProperty('archives_base_name') ?: 'ParadiseClient'
}

repositories {
    mavenCentral()

    maven {
        url 'https://jitpack.io'
    }

    maven {
        url 'https://repo.viaversion.com'
    }

    flatDir {
        dirs 'libs'
    }
}

dependencies {
    minecraft(
            "com.mojang:minecraft:${project.minecraft_version}"
    )
    implementation(
            "net.fabricmc:fabric-loader:${project.loader_version}"
    )
    implementation(
            "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    )

    def shadowLibs = [
            "net.sf.trove4j:trove4j:3.0.3",
            "com.github.Vatuu:discord-rpc:1.6.2",
            "dev.dejvokep:boosted-yaml:${boosted_yaml_version}",
            "com.viaversion:nbt:5.0.0"
    ]
    shadowLibs.each {
        shadow(implementation(it)) {
            exclude group: "it.unimi.dsi", module: "fastutil"
        }
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "git_hash": gitHash,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

tasks.named('sourcesJar') {
    dependsOn tasks.named('generateGitProperties')
}

shadowJar {
    configurations = [project.configurations.shadow]
    archiveClassifier.set("shaded")
    relocate "com.viaversion.nbt", "net.paradise_client.nbt"
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveClassifier.set("dev")
    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}" }
    }
    dependsOn(shadowJar)
    from(project.zipTree(tasks.shadowJar.archiveFile.get())) {
        exclude "META-INF/INDEX.LIST", "META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA"
    }
}
